---
- name: install wordpress
  hosts: prod
  vars_files:
    - files/secrets/credentials.yml
  vars:
    db_user: toto
    db_password: toto
    db_name: wordpress
    docker_network_name: wordpress_network
  
  tasks:
    - name: Create a network with options
      docker_network:
        name: "{{ docker_network_name }}"
        driver: bridge
        driver_options:
          subnet: "11.0.0.0/24"
    - name: Create container MySQL
      docker_container:
        name: mysql
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_USER: "{{ db_user }}"
          MYSQL_PASSWORD: "{{ db_password }}"
          MYSQL_DATABASE: "{{ db_name }}"
        networks:
          - name: "{{ docker_network_name }}"
        volumes:
          - mysqldir:/var/lib/mysql
    - name: Create container Wordpress
      docker_container:
        name: wordpress
        image: wordpress
        env:
          WORDPRESS_DB_HOST: "mysql"
          WORDPRESS_DB_USER: "{{ db_user }}"
          WORDPRESS_DB_PASSWORD: "{{ db_password }}"
          WORDPRESS_DB_NAME: "wordpress"
        networks:
          - name: "{{ docker_network_name }}"
        volumes:
          - "wordpress:/var/www/html"
        ports:
          - "80:80"